Trainer:
  model_name: DA3D
  lr: 0.001
  weight_decay: 0.0005
  epoches: 2400
  save_every_n_epochs: 1
  num_gpus: 1
  check_val_every_n_epoch: 25


  train:
    batch_size: 8
    n_workers: 8
    pin_mem: True
    shuffle: True

  val:
    batch_size: 8
    n_workers: 8
    pin_mem: True
    shuffle: False


TrainDataset:
  data_dir: /data/zero/1_Data/E_ThirdParty/Peract_packaged
