
Trainer:
  model_name: DA3D
  lr: 0.0001
  weight_decay: 0.0005
  epoches: 400
  batch_size: 8
  n_workers: 8
  pin_mem: True
  num_gpus: 1
  shuffle: True

TrainDataset:
  data_dir: /data/zero/1_Data/B_Preprocess/DA3D
  tasks_to_use: put_groceries_in_cupboard
  cache_dataset_init_path: /media/jian/ssd4t/zero/1_Data/D_Cache_init/2025-04-18-18-45-58cache_dataset_init_path.pkl
  image_rescales: [0.75,1.25]
  instr_embed_file: '/data/zero/assets/instr_embeds_clip.npy'
  taskvar_instr_file: '/data/zero/assets/taskvars_instructions_peract.json'

DiffuserActor:
  Policy:
    num_timesteps: 100
    use_instruction: False
    action_space: 'eePose' # 'eePose', 'JP'

  FeatureExtractor:
    backbone: 'clip'
    image_size: [256,256]
    embedding_dim: 120
    num_sampling_level: 1
    nhistory: 8
    num_vis_ins_attn_layers: 2
    fps_subsampling_factor: 5
    use_instruction: True


  ActionHead:
    embedding_dim: 120
    use_instr: True
    nhist: 8
    lang_enhanced: False
    horizon: 1

    

# Checking
# nhist