

save_path: ./1_Data/A_Selfgen/trajectory/test2
all_task_file: ./assets/peract_tasks.json
image_size:
  - 256
  - 256
renderer: opengl
processes: 2
episodes_per_task: 10
variations: -1
offset: 0
state: false
tasks:
  - place_shape_in_shape_sorter_peract
  - close_jar_peract
  - meet_off_grill_peract
  - push_buttons_peract
  - reach_target

var: [1]
num: 100

traj_flag: 1