
B_Preprocess: /data/zero/1_Data/B_Preprocess/0.01all_with_path_with_positionactions
horizon: 8
unit_test: False

Train:
  name: test
  tasks_to_use: "close_jar"
  n_workers: 1
  batch_size: 1
  epochs: 6000
  lr: 0.001
  pin_mem: True
  num_gpus: 1
  shuffle: True

TRAIN_DATASET:
  data_dir: '/data/zero/1_Data/B_Preprocess/0.01all_with_path_with_positionactions'
  instr_embed_file: '/data/zero/assets/instr_embeds_clip.npy'
  taskvar_instr_file: '/data/zero/assets/taskvars_instructions_peract.json'
  taskvar_file: '/data/zero/assets/taskvars_peract.json'
  num_points: 4096
  xyz_shift: center # none, center, gripper
  xyz_norm: False
  use_height: True

  rot_type: euler_disc # quat, rot6d, euler, euler_delta, euler_disc
  pos_type: disc # disc, cont
  instr_embed_type: 'all' # last, all

  rm_robot: box_keep_gripper  # none, gt, box, box_keep_gripper
  augment_pc: True
  aug_max_rot: 45
  same_npoints_per_example: False
  pos_bins: null
  pos_bin_size: null
  pos_heatmap_type: 'dist' # plain, dist
  pos_heatmap_no_robot: True
  real_robot: False
  euler_resolution: 1
  rm_table: True
  rm_pc_outliers: False
  rm_pc_outliers_neighbors: 25
  sample_points_by_distance: False
  variations_to_use: null
  tasks_to_use: "close_jar"



ActionHead:
  horizon: 8
  action_dim: 8
  global_cond_dim: 256 #与
  diffusion_step_embed_dim: 256



Dataset:
  voxel_size: 0.01
  txt_ft_size: 512
  context_channels: 256
  txt_reduce: 'attn' # mean, attn


Tmp:
  txt_ft_size: 512
  context_channels: 256
  txt_reduce: 'attn' # mean, attn