
test: 1
Trainer:
  model_name: DP
  lr: 0.00001
  weight_decay: 0.00001
  epoches: 2400
  max_steps: -1
  save_every_n_epochs: 100
  num_gpus: 1
  check_val_every_n_epoch: 25


  train:
    batch_size: 8
    n_workers: 8
    pin_mem: True
    shuffle: True

  val:
    batch_size: 8
    n_workers: 8
    pin_mem: True
    shuffle: False


TrainDataset:
  data_dir: /data/zero/1_Data/B_Preprocess/DP/keypose/singleVar
  tasks_to_use: null
  cache_dataset_init_path: null
  image_rescales: [0.75,1.25]
  instr_embed_file: '/data/zero/assets/instr_embeds_clip.npy'
  taskvar_instr_file: '/data/zero/assets/taskvars_instructions_peract.json'
  taskvar_file: '/data/zero/assets/taskvars_peract.json'
  num_points: 4096
  augmentation: False

DP:
  Policy:
    num_timesteps: 100
    use_instruction: False
    DDPM:
      beta_1: 0.0001
      beta_T: 0.02
      T: 100
    collision_loss: False


  ActionHead:
    d_model: 512
    d_instr: 512
    d_ffw: 512
    n_heads: 8
    n_features: 96
    horizon: 8
    n_cross_attn_layers: 4
    n_self_attn_layers: 4

    action_mode: 'JP' # eePose, JP
    pos_norm_type: null
    rot_norm_type: ortho6d # ortho6d, euler


# region tmp
Dataset:
  voxel_size: 0.01
  txt_ft_size: 512
  context_channels: 256
  txt_reduce: 'attn' # mean, attn
  max_seq_len: 20


