

exp_dir: /media/jian/ssd4t/zero/2_Train/0420_1/version_0
epoch: null
device: 'cuda'  # cpu, cuda
image_size: [256, 256]
max_tries:  3
max_steps:  15

microstep_data_dir: ''
queue_size: 20
taskvar_file: '/data/zero/assets/taskvars_peract.json'
num_ensembles:  1
save_obs_outs_dir:  None
best_disc_pos: 'max'  # max, ens1
record_video:  False
video_dir: null
not_include_robot_cameras: False
video_rotate_cam:  False
video_resolution:  480
real_robot: False

############################
# sbatch
############################
ckpt_step: 220000
seed: 2025
num_workers : 1
num_demos : 20
config: null
name: null
checkpoint: null
tasks_to_use: put_groceries_in_cupboard
headless: 0
action_mode: 'eePose'  # eePose, JP