exp_dir: /media/jian/ssd4t/zero/2_Train/version_0
epoch: 449
device: 'cuda'  # cpu, cuda
image_size: [256, 256]
max_tries:  3
max_steps:  50

microstep_data_dir: ''
queue_size: 20
taskvar_file: './assets/taskvars_peract.json'
num_ensembles:  1
save_obs_outs_dir:  None
best_disc_pos: 'max'  # max, ens1
ckpt_step: 2200
# record video
video_dir: null
not_include_robot_cameras: False
video_rotate_cam:  False
video_resolution:  480
real_robot: False


seed: 42
num_workers : 1
num_demos : 5 # 每个var eval多少次
config: null
name: null
checkpoint: null
tasks_to_use: push_buttons
variations_to_use: [0]

headless: 0
record_video: 1