
TrainDataset:
  data_dir: /media/jian/ssd4t/zero/1_Data/B_Preprocess/DA3D
  tasks_to_use: null
  cache_dataset_init_path: /media/jian/ssd4t/zero/1_Data/D_Cache_init/2025-03-22-11-15-14cache_dataset_init_path.pkl
  image_rescales: [0.75,1.25]

DiffuserActor:
  Policy:
    num_timesteps: 100
    use_instruction: False
  FeatureExtractor:
    backbone: 'clip'
    image_size: [256,256]
    embedding_dim: 120
    num_sampling_level: 1
    nhistory: 3
    num_vis_ins_attn_layers: 2
    fps_subsampling_factor: 5
    use_instruction: True


  ActionHead:
    embedding_dim: 120
    use_instruction: False
    rotation_parametrization: 'quat'
    nhist: 3
    lang_enhanced: False
    action_dim: 8
    
