apiVersion: batch/v1
kind: Job
metadata:
  name: data-processor
spec:
  backoffLimit: 0
  template:
    metadata:
      name: data-processor
    spec:
      containers:
      - name: processor
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - echo "Starting data processing...";
          for i in {1..100}; do
            echo "Processing batch $i";
            sleep 2;
          done;
          echo "Data processing completed!"
      restartPolicy: Never