apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zero
spec:
  accessModes:
    - ReadWriteMany # So you can run multiple training pods with the same PVC
  resources:
    requests:
      storage: 500Gi # You can change this value up to 1000Gi