apiVersion: batch/v1
kind: Job
metadata:
  name: 0515_01_eePose_3050 # Your training job name
  
spec:
  backoffLimit: 0   # add this line so --> If your pod failed, the training job will stop.
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: gitlab-docker-secret
      volumes:
        - name: shared-memory # This is to resolve the dataloader OOM issue.
          emptyDir:
            medium: Memory
        - name: dataset-volume
          persistentVolumeClaim:
            claimName: zero      # <------- your PVC name    kubectl get pvc

      containers:
        - name: zero-container # It is recommended to name your container according to the project
          image: docker.aiml.team/jian.zhou/test:latest # You can reuse this image for different projects if their python dependencies are the same.
          imagePullPolicy: Always
          stdin: true
          tty: true
          command: ["/bin/bash", "-c"]
          args: 
              - |
                cd /data/zero
                git pull
                pip install -e .
                cd /data/zero/6_ThirdParty/codebase
                git stash
                git pull
                pip uninstall -y codebase
                pip install -e .

                cd /data/zero
                python -c "import torch; print(torch.cuda.is_available());print(torch.__version__);print(torch.version.cuda)"
                nvidia-smi
                pip install numba
                python /data/zero/zero/expForwardKinematics/trainer_FK_all.py --model DP_traj_zarr


          resources:
            limits:
              cpu: 8
              nvidia.com/gpu: 4           # <------- If you don't need any of GPUs, Please comment-out this line.
              memory: 60Gi
            requests:
              cpu: 8
              nvidia.com/gpu: 4           # <------- If you don't need any of GPUs, Please comment-out this line.
              memory: 60Gi
          
            


          volumeMounts:
            - name: dataset-volume
              mountPath: /data
            - name: shared-memory
              mountPath: /dev/shm
          env:
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                    name: gitlab-token  # kubectl get secrets
                    key:  access-token