dataset_name: "rlbench_peract"



cameras: ["left_shoulder", "right_shoulder", "wrist","front"]
image_size: "256,256"
max_episodes_per_task: -1
path_instructions: "/hpcfs/users/a1946536/data/peract/Peract_packaged/instructions.pkl"
seed: 0
tasks: [
    "place_cups", "close_jar", "insert_onto_square_peg", "light_bulb_in",
    "meat_off_grill", "open_drawer", "place_shape_in_shape_sorter",
    "place_wine_at_rack_location", "push_buttons", "put_groceries_in_cupboard",
    "put_item_in_drawer", "put_money_in_safe", "reach_and_drag",
    "slide_block_to_color_target", "stack_blocks", "stack_cups",
    "sweep_to_dustpan_of_size", "turn_tap"
]
variations: 0 #

checkpoint: null
accumulate_grad_batches: 1
val_freq: 4000 
path_gripper_location_boundaries: "/workspace/zero/zero/v1/tasks/18_peract_tasks_location_bounds.json" # changed in main
gripper_loc_bounds_buffer: 0.04
eval_only: 0

# Training and validation datasets
path_dataset: "/hpcfs/users/a1946536/data/peract/Peract_packaged/train"
path_valset: "/hpcfs/users/a1946536/data/peract/Peract_packaged/val"

dense_interpolation: 1
interpolation_length: 2

# Logging
base_log_dir: "train_logs"
exp_log_dir: "Actor_18Peract_100Demo_multitask"
run_log_dir: log/ddd/log

# Main training parameters
num_workers: 15
batch_size: 8
batch_size_val: 1
cache_size: 600
cache_size_val: 0
lr: 0.0001
wd: 0.005  # Used only for CALVIN
train_iters: 600000 
val_iters: -1  # -1 means heuristically-defined
max_episode_length: 5  # -1 for no limit
shuffle: 1
# Data augmentations
image_rescale: "0.75,1.25"  # (min, max), "1.0,1.0" for no rescaling

# Model
backbone: "clip"  # One of "resnet", "clip"
embedding_dim: 120
num_vis_ins_attn_layers: 2
use_instruction: 1
rotation_parametrization: 6D 
quaternion_format: xyzw
diffusion_timesteps: 100
keypose_only: 1
num_history: 3
relative_action: 0
lang_enhanced: 0
fps_subsampling_factor: 5















