
dataset_name: pusht

dataset_rlbench:
  dataset_train_path: /data/rlbench
  ckpt_path: /data/ckpt
  batch_size: 128
  shuffle: True
  num_workers: 8
  model:
      d_model: 512
      ff_dim: 2048
      num_layers: 6
      nhead: 8
      dim_feedforward: 2048
      dropout: 0.1
      activation: relu
      layer_norm_eps: 0.00001
      bias: True
      num_image: 5
      device: cuda
      dtype: float32
      action_space: 8
  
  
dataset_pusht:
  dataset_train_path: /data/pusht
  ckpt_path: /data/ckpt
  batch_size: 128
  shuffle: True
  num_workers: 16
  model:
    d_model: 512
    ff_dim: 2048
    num_layers: 6
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    activation: relu
    layer_norm_eps: 0.00001
    bias: True
    num_image: 1
    device: cuda
    dtype: float32
    action_space: 2
  