
############################################
# suplementary configs for data management
############################################
pl_flag: True
exp_name: 'exp_base_insert_peg_0.005'
selfgen_dir: '/data/zero/1_Data/A_Selfgen/seed42'
preprocess_dir: '/data/zero/1_Data/B_Preprocess/insert_0.005'
tasks_to_use: ['insert_onto_square_peg']
log_dir: '/data/zero/2_Train'

############################################
# Trainning configs
############################################
TRAIN:
  resume_training: True
  resume_encoder_only: False
  freeze_params:
    encoder: False
    decoder: False

  train_batch_size: 4
  # val_batch_size: 1

  gradient_accumulation_steps: 1
  num_epochs: null
  epoches: 800
  num_train_steps: 20000
  warmup_steps: 2000
  log_steps: 1000
  save_steps: 10000
  val_steps: 10000

  optim: 'adamw'
  learning_rate: 0.0001
  lr_sched: 'cosine' # inverse_sqrt, linear, cosine, cosine_cycle
  num_cosine_cycles: null # float
  betas: [0.9, 0.98]
  weight_decay: 0.05
  grad_norm: 10
  n_workers: 1
  pin_mem: True


TRAIN_DATASET:
  # data_dir: '/media/jian/ssd4t/selfgen/after_shock3'
  instr_embed_file: '/data/lotus/peract/train/keysteps_bbox_pcd/instr_embeds_clip.npy'
  taskvar_instr_file: '/data/zero/zero/v4/models/lotus/assets/taskvars_instructions_peract.json'
  taskvar_file: '/data/zero/zero/v4/models/lotus/assets/taskvars_peract.json'
  num_points: 100000
  xyz_shift: center # none, center, gripper
  xyz_norm: False
  use_height: True
  sample_points_by_distance: False
  rot_type: euler_disc # quat, rot6d, euler, euler_delta, euler_disc
  pos_type: disc # disc, cont
  instr_embed_type: 'all' # last, all
  all_step_in_batch: True
  include_last_step: False
  rm_table: True
  rm_robot: box_keep_gripper  # none, gt, box, box_keep_gripper
  augment_pc: True
  aug_max_rot: 45
  same_npoints_per_example: False
  rm_pc_outliers: False
  rm_pc_outliers_neighbors: 25
  pos_bins: 15
  pos_bin_size: 0.01
  pos_heatmap_type: 'dist' # plain, dist
  pos_heatmap_no_robot: True
  real_robot: False
  euler_resolution: 5


MODEL:
  model_class: 'SimplePolicyPTV3CA'
  ptv3_config:
    in_channels: 7
    order: ["z", "z-trans", "hilbert", "hilbert-trans"]
    stride: [2, 2, 2, 2]
    enc_depths: [1, 1, 1, 1, 1]
    enc_channels: [64, 128, 256, 512, 768]
    enc_num_head: [2, 4, 8, 16, 32]
    enc_patch_size: [128, 128, 128, 128, 128]
    dec_depths: [1, 1, 1, 1]
    dec_channels: [128, 128, 256, 512]
    dec_num_head: [4, 4, 8, 16]
    dec_patch_size: [128, 128, 128, 128]
    mlp_ratio: 4
    qkv_bias: True
    qk_scale: null
    qk_norm: True
    scaled_cosine_attn: False
    attn_drop: 0.1
    proj_drop: 0.1
    drop_path: 0
    pre_norm: True
    shuffle_orders: True
    enable_rpe: False
    enable_flash: False
    upcast_attention: False
    upcast_softmax: False
    cls_mode: False
    pdnorm_bn: False
    pdnorm_ln: False
    pdnorm_decouple: False
    pdnorm_adaptive: False
    pdnorm_affine: True
    pdnorm_conditions: null
    pdnorm_only_decoder: False
    add_coords_in_attn: 'none' # none, qk, qkv

  action_config:
    voxel_size: 0.005 # 1cm
    context_channels: 256

    txt_ft_size: 512
    max_txt_len: 77
    txt_reduce: 'attn' # mean, attn
    use_ee_pose: False
    use_step_id: False

    max_steps: 30
    
    reduce: 'max' # max, mean, attn, multiscale_max
    max_traj_len: 1 # predicted trajectory len
    dim_actions: 7  # (xyz, quaternion, openness)
    pos_pred_type: 'heatmap_disc'  # heatmap_mlp, regression, regression_delta, heatmap_disc
    pos_heatmap_temp: 0.1
    rot_pred_type: 'euler_disc'     # quat, rot6d, euler, euler_delta, euler_disc

    dropout: 0.2

    pos_bins: 15
    pos_bin_size: 0.01
    best_disc_pos: max # max, ens1

  loss_config:
    pos_weight: 1
    rot_weight: 1



